services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /mnt/cyberserver/www/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/cyberserver/www/ssl:/etc/nginx/ssl
      - /mnt/cyberserver/www/html:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - web-network

  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - /mnt/cyberserver/www/html:/var/www/html
      - /mnt/cyberserver/www/php/custom_ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
